// Generated by https://quicktype.io

export interface EmailAuth {
    detail: string;
}

export interface EmailToken {
    token: string;
}

export interface Profile {
    id: number;
    user: User;
    type: 'family' | 'friend' | 'colleague';
    parent: null | User;
    childs: Profile[];
    language: 'it' | 'es' | 'en';
    plus: number;
}

export interface User {
    id?: number;
    username?: string;
    first_name: string;
    last_name: string;
    email: string;
}

export interface UserError {
    first_name: string[];
    last_name: string[];
    email: string[];
    non_field_errors: string[];
};
