// Generated by https://quicktype.io

export interface EmailAuth {
    detail: string;
}
// Generated by https://quicktype.io

export interface EmailToken {
    token: string;
}
// Generated by https://quicktype.io

export interface Profile {
    id: number;
    user: User;
    type: string;
    parent: null | User;
    childs: Profile[];
    language: string;
    plus: number;
}

export interface User {
    id: number;
    username?: string;
    first_name: string;
    last_name: string;
    email: string;
}

export interface UserError {
    first_name: string[];
    last_name: string[];
    email: string[];
    non_field_errors: string[];
};
