# Generated by Django 3.2 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español')], default='en', max_length=2),
        ),
    ]
