# Generated by Django 3.2 on 2022-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
