# Generated by Django 4.1.3 on 2022-11-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_keys_remove_subscription_keys_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='keys',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.keys'),
        ),
    ]
