# Generated by Django 4.1.3 on 2022-11-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_subscription_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='p265dh',
            new_name='p256dh',
        ),
    ]
