# Generated by Django 4.1.3 on 2022-11-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_rename_p265dh_keys_p256dh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='keys',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.keys'),
        ),
    ]
