# Generated by Django 4.1.3 on 2022-12-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_alter_subscription_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
