# Generated by Django 4.1.3 on 2022-12-20 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0010_remove_userprofile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_agent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'user_agent', 'endpoint')},
        ),
    ]
