# Generated by Django 4.1.3 on 2023-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_alter_subscription_options_subscription_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'user_agent', 'endpoint'), name='unique_subscription_per_device'),
        ),
    ]
