# Generated by Django 4.1.6 on 2023-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(2, 'family'), (3, 'friend'), (5, 'colleague'), (7, 'friend of family'), (11, 'distant family')], default=2),
        ),
    ]
