# Generated by Django 3.2 on 2022-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Freetext'), (1, 'SingleSelect'), (2, 'MultiSelect'), (3, 'SingleSelectOther'), (4, 'MultiSelectOther')], default=0),
        ),
    ]
