# Generated by Django 3.2 on 2022-07-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='isMultiSelect',
        ),
        migrations.AddField(
            model_name='question',
            name='isMultiSelect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
