# Generated by Django 3.2 on 2022-07-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20220704_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inbox.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
