# Generated by Django 3.2 on 2022-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20220704_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.RemoveField(
            model_name='response',
            name='option',
        ),
        migrations.AddField(
            model_name='response',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='inbox.Option'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_response'),
        ),
    ]
