# Generated by Django 3.2 on 2022-07-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_auto_20220704_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
