# Generated by Django 3.2 on 2022-11-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_message_option_prerequisite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='option_prerequisite',
            new_name='option_pre',
        ),
    ]
