# Generated by Django 4.1.3 on 2022-11-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0011_alter_message_options_alter_message_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
