# Generated by Django 4.1.3 on 2022-12-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0013_alter_message_options_alter_response_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at']},
        ),
    ]
