# Generated by Django 4.1.3 on 2023-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0015_alter_message_subject_alter_question_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('question', 'user', 'active', 'deleted_at'), name='unique_active_response_per_user_and_question'),
        ),
    ]
