# Generated by Django 4.1.3 on 2023-01-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0016_alter_response_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
    ]
