# Generated by Django 4.1.6 on 2023-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0017_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audience',
            field=models.IntegerField(choices=[(2, 'family'), (3, 'friend'), (5, 'colleague'), (7, 'friend of family'), (11, 'distant family'), (6, 'family & friend'), (10, 'family & colleague'), (14, 'family & friend of family'), (22, 'family & distant family'), (15, 'friend & colleague'), (21, 'friend & friend of family'), (33, 'friend & distant family'), (35, 'colleague & friend of family'), (55, 'colleague & distant family'), (77, 'friend of family & distant family'), (30, 'family & friend & colleague'), (42, 'family & friend & friend of family'), (66, 'family & friend & distant family'), (70, 'family & colleague & friend of family'), (110, 'family & colleague & distant family'), (154, 'family & friend of family & distant family'), (105, 'friend & colleague & friend of family'), (165, 'friend & colleague & distant family'), (231, 'friend & friend of family & distant family'), (385, 'colleague & friend of family & distant family'), (210, 'family & friend & colleague & friend of family'), (330, 'family & friend & colleague & distant family'), (462, 'family & friend & friend of family & distant family'), (770, 'family & colleague & friend of family & distant family'), (1155, 'friend & colleague & friend of family & distant family'), (2310, 'family & friend & colleague & friend of family & distant family')], default=30),
        ),
    ]
