# Generated by Django 3.2 on 2022-10-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.TextField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_or_state',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
