# Generated by Django 3.2 on 2022-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plus',
            field=models.IntegerField(default=0),
        ),
    ]
