# Generated by Django 3.2 on 2022-10-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('picture', models.ImageField(upload_to='pictures/', verbose_name='Header picture')),
                ('tag', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('picture', models.ImageField(upload_to='pictures/', verbose_name='Header picture')),
                ('type', models.IntegerField(choices=[(0, 'Accomodations'), (1, 'Food'), (2, 'Attractions'), (3, 'Tips'), (4, 'Travel')])),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.contentstring')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
