# Generated by Django 3.2 on 2022-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
