# Generated by Django 3.2 on 2022-10-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('info', '0002_auto_20221016_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ice-breaker'), (1, 'Ceremony'), (2, 'Reception'), (3, 'Dinner'), (4, 'Dance')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='information_subject', to='shared.contentstring'),
            preserve_default=False,
        ),
    ]
