# Generated by Django 3.2 on 2022-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20221107_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ice-breaker'), (1, 'Ceremony'), (2, 'Reception'), (3, 'Dinner'), (4, 'Dance'), (5, 'Before')]),
        ),
    ]
