# Generated by Django 3.2 on 2022-11-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20221107_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='audience',
            field=models.IntegerField(choices=[(2, 'family'), (3, 'friend'), (5, 'colleague'), (6, 'family & friend'), (10, 'family & colleague'), (15, 'friend & colleague'), (30, 'all')], default=30),
        ),
    ]
