# Generated by Django 4.1.3 on 2022-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_photo_options_alter_information_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Before'), (1, 'Ice-breaker'), (2, 'Ceremony'), (3, 'Reception'), (4, 'Dinner'), (5, 'Dance')], default=0),
        ),
    ]
