# Generated by Django 4.1.3 on 2022-12-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_information_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Calendar'), (1, 'Maps')])),
                ('content', models.TextField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.information')),
            ],
            options={
                'unique_together': {('info', 'type')},
            },
        ),
    ]
