# Generated by Django 4.1.3 on 2022-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_informationwidget_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationwidget',
            name='type',
            field=models.IntegerField(choices=[(0, 'calendar'), (1, 'maps')]),
        ),
    ]
