# Generated by Django 4.1.3 on 2022-12-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_remove_photo_caption_photo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='type',
            field=models.IntegerField(choices=[(0, 'Venues'), (1, 'Food'), (2, 'Attractions'), (3, 'Tips'), (4, 'Travel'), (5, 'Events'), (6, 'Gifts')]),
        ),
    ]
