# Generated by Django 4.1.3 on 2022-12-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_information_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['type', 'pk']},
        ),
    ]
