# Generated by Django 4.1.3 on 2022-12-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_information_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['type', 'pk']},
        ),
    ]
