# Generated by Django 4.1.3 on 2023-01-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_delete_attachment_remove_location_address_and_more'),
        ('info', '0018_alter_information_options_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='shared.contentstring'),
        ),
    ]
