# Generated by Django 4.1.3 on 2023-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_alter_information_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informationwidget',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='informationwidget',
            constraint=models.UniqueConstraint(fields=('info', 'type'), name='unique_widget_per_info_type'),
        ),
    ]
