# Generated by Django 4.1.6 on 2023-02-04 14:43

from django.db import migrations, models


def combine_types(apps, schema_editor):
    Information = apps.get_model('info', 'Information')
    for info in Information.objects.filter(type__in=[0, 1, 2]):
        info.type = 3
        info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_alter_informationwidget_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(combine_types),
        migrations.AlterField(
            model_name='information',
            name='type',
            field=models.IntegerField(
                choices=[(3, 'Tips'), (4, 'Travel'), (5, 'Events'), (6, 'Gifts')]),
        ),
    ]
