# Generated by Django 5.0 on 2024-01-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_information_audience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['pk']},
        ),
    ]
