# Generated by Django 4.1.3 on 2022-12-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_remove_entry_id_entry_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at']},
        ),
    ]
