# Generated by Django 4.1.6 on 2023-06-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'entries'},
        ),
    ]
