apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wedding.fullname" . }}
  labels:
    app: {{ include "wedding.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "wedding.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "wedding.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ include "wedding.fullname" . }}
          envFrom:
            - secretRef:
                name: wedding
            - configMapRef:
                name: wedding
          ports:
            - containerPort: 8000
              name: gunicorn
          {{- if .Values.resources }}
          resources:
            {{- if .Values.resources.limits }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            {{- end}}
            {{- if .Values.resources.requests }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            {{- end}}
          {{- end}}

          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.service.port }}
              httpHeaders:
              - name: Accept
                value: application/json
              {{- if .Values.ingress.enabled }}
              {{- with (first .Values.ingress.hosts) }}
              - name: Host
                value: {{ .host }}
              {{- end }}
              {{- end }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.port }}
              httpHeaders:
              - name: Accept
                value: application/json
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

