apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wedding.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: wedding
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default "latest"}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                sleep 60 &&
                python manage.py migrate
          envFrom:
            - secretRef:
                name: wedding
            - configMapRef:
                name: wedding
      restartPolicy: Never
      parallelism:
