name: frontend

on:
  push:
    branches: [master, develop]
    paths:
      - "wedding-frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wedding-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          file: ./wedding-frontend/docker/Dockerfile
          context: ./wedding-frontend
          platforms: linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wedding-frontend:develop
          cache-from: type=local,src=/tmp/${{ github.ref_name }}/.buildx-cache
          cache-to: type=local,dest=/tmp/${{ github.ref_name }}/.buildx-cache-new
          build-args: |
            ENV_MODE=${{ fromJSON('{"master": "production", "develop": "staging"}')[github.ref_name] }}
      - name: Move cache
        run: |
          rm -rf /tmp/${{ github.ref_name }}/.buildx-cache
          mv /tmp/${{ github.ref_name}}/.buildx-cache-new /tmp/${{ github.ref_name }}/.buildx-cache


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Kubernetes
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Rollout deploy
        if: ${{ github.ref_name == 'master' }}
        run: kubectl rollout restart deploy frontend-wedding -n wedding
      - name: Rollout deploy stage
        if: ${{ github.ref_name == 'develop' }}
        run: kubectl rollout restart deploy frontend-wedding -n wedding-stg
